contraindicacao=[
    'esfacelo','AGE',
    'escara','AGE',
    'infectada','AGE',
    'seca','Alginato de Cálcio',
    'exudato','Alginato de Cálcio',
    'queimadura','Alginato de Cálcio',
    'ossos','Alginato de Cálcio',
    'tendões','Alginato de Cálcio',
    'estágio III','Alginato de Cálcio',
    'vasculares','Bota de Unna',
    'diabéticas','Bota de Unna',
    'queimaduras','Carvão Ativado',
    'hemorrágicas','Carvão Ativado',
    'escara','Carvão Ativado',
    'exsudato','Carvão Ativado',
    'granulação','Colagenase',
    'sudorese','Filme Transparente',
    'exsudato','Filme Transparente',
    'infectadas','Filme Transparente',
    'exsudato','Hidrocolóide',
    'infectadas','Hidrocolóide',
    'cavitárias','Hidrocolóide',
    'Região sacral','Hidrocolóide',
    'seca','Hidrofibra',
    'exsudato','Hidrogel',
    'pele íntegra','Hidrogel',
    'queimaduras 3','Hidrogel',
    
]